services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
    ports:
      - "1433:1433"

  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "5000:5000"
    environment:
      - DB_SERVER=db
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Password123
    depends_on:
      - db
